### ISSUE TITLE
Could not find nuget packages

### ISSUE THREAD

**Issue by Th3L0x** [v-hogood/MediaPipeTasks#1]
These packages are not present in nuget package manager:

- MediaPipeTasksCore  (android)
- MediaPipeTasksVision  (android)
- MediaPipeTasksText (android)
- MediaPipeTasksAudio (android)

**Comment by v-hogood** [comment]
They should be there now; it takes a little while for nuget.org to publish them.

**Comment by Th3L0x** [comment]
Thank you, it's working!

**Comment by v-hogood** [comment]
Great thanks for trying it!
